name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    env:
      endpoint: ${{ secrets.ENDPOINT }}
      accesskeyid: ${{ secrets.ACCESSKEYID }}
      secretaccesskey: ${{ secrets.SECRETACCESSKEY }}
      bucket: ${{ secrets.BUCKET }}
      sourcedir: /tmp
      loglevel: debug
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
      - name: Check out source
        uses: actions/checkout@v3
      - name: Install revive
        run: go install github.com/mgechev/revive@latest
      - name: Run linter
        run: revive -formatter friendly ./...
      - name: Build
        run: go build ./...
      - name: Test
        run: |
          sh ./run_tests.sh